version: '3'
services:

  lambda:
    image: lambci/lambda:nodejs10.x
    volumes:
      - ../:/var/task:delegated

  build:
    image: node:10
    working_dir: /app
    volumes:
      - ../:/app:delegated
